apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: sitecore-xp1-solr-init
  newName: scr.sitecore.com/sxp/sitecore-xp1-solr-init
  newTag: 10.4-ltsc2022
resources:
- solr-init.yaml
