apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../configmaps
  - ingress.yaml
  - configuration.yaml

replacements:
- source:
    fieldPath: data.solr-hostname
    kind: ConfigMap
    name: sitecore-hostnames
    version: v1
  targets:
  - select:
      group: networking.k8s.io
      kind: Ingress
      name: sitecore-ingress
      version: v1
    fieldPaths:
    - spec.rules.[host=solr-placeholder-hostname].host
  - select:
      group: networking.k8s.io
      kind: Ingress
      name: sitecore-ingress
      version: v1
    fieldPaths:
    - spec.tls.[secretName=global-solr-tls].hosts.0
