apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solr

resources:
  - solr.yaml
  - solr-external.yaml
  - zookeeper.yaml

images:
  - name: solr
    newName: solr
    newTag: "8.11.2"
  - name: zookeeper
    newName: zookeeper
    newTag: "3.7"

commonLabels:
  app.kubernetes.io/part-of: solrcloud